keys:
  - &admin age17rdudzmkasgj0l5dnqr64du00n9ljskrllml9zq7n272rrvwnehsdjdsa4
  - &host age1t8pc23ayxgac5vm9fdfkjkt70f6ad3af9yah6jt8627z8hn5c4ys849kvx
creation_rules:
  - path_regex: secrets/[^/]+\.json$
    key_groups:
      - age:
          - *admin
          - *host
