pcall(require, "impatient")
require'settings'
require'autocommands'
require'theme'
require'lsp'
require'mappings'
require'statusline'
require'plugins'
require'plugins.telescope'
require'plugins.tree-toggle'
require'plugins.nvim-cmp'
require'plugins.treesitter'
require'plugins.venn-nvim'
require'plugins.gitsigns'
require'plugins.nvim-rooter'
-- require'plugins.idris2-nvim'
require'plugins.barbar-nvim'
