pcall(require, "impatient")
require'settings'
require'autocommands'
require'theme'
require'lsp'
require'mappings'
require'plugins'
require'plugins.galaxyline'
require'plugins.telescope'
require'plugins.tree-toggle'
require'plugins.nvim-cmp'
require'plugins.treesitter'
require'plugins.venn-nvim'
require'plugins.idris2-nvim'
require'plugins.trouble'
