-- require('tabnine').setup({
--   disable_auto_comment=true,
--   accept_keymap="<C-s>",
--   dismiss_keymap = "<C-x>",
--   debounce_ms = 800,
--   suggestion_color = {gui = "#808080", cterm = 244},
--   exclude_filetypes = {"TelescopePrompt", "NvimTree"},
--   log_file_path = "/home/jonathanl/.tabnine.log" , -- absolute path to Tabnine log file
-- })
